import = ["~/.config/alacritty/themes/themes/gruvbox-dark.toml"]

live_config_reload = true

#[cursor]
#blinking = "On"

[env]
TERM = "alacritty"

[font]
size = 14

[font.normal]
family = "RobotoMono Nerd Font Mono"
style = "Medium"
[font.italic]
family = "RobotoMono Nerd Font Mono"
style = "Medium Italic"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[scrolling]
history = 100000

[window]
dynamic_title = false
title = "Terminal"
padding = { x = 6, y = 6 }
