[env]
TERM = "alacritty"
term = "xterm-256color"

[font]
size = 13

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"
[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"
[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Medium"

[scrolling]
history = 100000

[window]
title = "Terminal"
dynamic_padding = true
padding = { x=5, y=2 }
dynamic_title = false
decorations = "buttonless"

[general]
live_config_reload = true
import = ["~/.config/alacritty/themes/themes/catppuccin-macchiato.toml"]
