return {
  "akinsho/bufferline.nvim",
  version = "*",
  dependencies = { "nvim-tree/nvim-web-devicons" },
  event = "VeryLazy",
  keys = {
    { "<S-h>", "<cmd>BufferLineCyclePrev<cr>", desc = "Prev buffer" },
    { "<S-l>", "<cmd>BufferLineCycleNext<cr>", desc = "Next buffer" },
    { "<leader>x", "<cmd>bdelete<cr>", desc = "Close buffer" },
    { "<leader>tn", "<cmd>tabnew<cr>", desc = "New tab" },
  },
  opts = {
    options = {
      mode = "tabs",
      diagnostics = "nvim_lsp",
      always_show_bufferline = false,
      separator_style = "thin",
      offsets = {
        {
          filetype = "NvimTree",
          text = "File Explorer",
          highlight = "Directory",
          separator = true,
        },
      },
    },
    highlights = {
      fill = { bg = "none" },
      background = { bg = "none" },
      buffer_selected = { bg = "none", bold = true, italic = false },
      buffer_visible = { bg = "none" },
      close_button = { bg = "none" },
      close_button_visible = { bg = "none" },
      close_button_selected = { bg = "none" },
      separator = { bg = "none" },
      separator_selected = { bg = "none" },
      separator_visible = { bg = "none" },
      tab = { bg = "none" },
      tab_selected = { bg = "none" },
      tab_close = { bg = "none" },
      duplicate = { bg = "none" },
      duplicate_selected = { bg = "none", italic = false },
      duplicate_visible = { bg = "none" },
      indicator_selected = { bg = "none" },
      indicator_visible = { bg = "none" },
      modified = { bg = "none" },
      modified_selected = { bg = "none" },
      modified_visible = { bg = "none" },
    },
  },
}
