#!/usr/bin/env bash

# load scripting additions
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

#
# Config
#
SPACE=8
yabai -m config layout bsp
yabai -m config top_padding $SPACE
yabai -m config bottom_padding $SPACE
yabai -m config left_padding $SPACE
yabai -m config right_padding $SPACE
yabai -m config window_gap $SPACE

yabai -m config auto_balance off
yabai -m config split_ratio 0.5
yabai -m config window_shadow off

#
# Rules
#
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^AppCleaner$" manage=off
yabai -m rule --add app="^Simulator$" manage=on

#
# Setup spaces
#
function setup_space {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
}

setup_space 1 web 
setup_space 2 code
setup_space 3 communication 
setup_space 4 media

yabai -m rule --add app="^Arc$" space=1
open -a "Arc"
yabai -m rule --add app="^Alacritty$" space=2
open -a "Alacritty"
yabai -m rule --add app="^Discord$" space=3
yabai -m rule --add app="^Spotify$" space=4

yabai -m rule --apply
