#!/usr/bin/env bash

# load scripting additions
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

#
# Config
#
yabai -m config mouse_follows_focus on

SPACE=10
yabai -m config layout bsp
yabai -m config top_padding $SPACE
yabai -m config bottom_padding $SPACE
yabai -m config left_padding $SPACE
yabai -m config right_padding $SPACE
yabai -m config window_gap $SPACE

yabai -m config auto_balance off
yabai -m config split_ratio 0.5
yabai -m config window_shadow off

#
# Rules
#
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^AppCleaner$" manage=off
yabai -m rule --add app="^Simulator$" manage=on
