#!/usr/bin/env bash

# change window focus within space
alt - j: yabai -m window --focus south
alt - k: yabai -m window --focus north
alt - h: yabai -m window --focus west
alt - l: yabai -m window --focus east

# focus display
ctrl + alt - o: yabai -m display --focus next
ctrl + alt - i: yabai -m display --focus prev

# move window to display 
ctrl + shift + alt - j: yabai -m display --focus prev
ctrl + shift + alt - k: yabai -m display --focus next

# toggle window float
shift + alt - t: yabai -m window --toggle float --grid 4:4:1:1:2:2

# maximize a window
shift + alt - f: yabai -m window --toggle zoom-fullscreen

# balance out tree of windows (resize to occupy same area)
shift + alt - e: yabai -m space --balance

# swap windows
shift + alt - j: yabai -m window --swap south
shift + alt - k: yabai -m window --swap north
shift + alt - h: yabai -m window --swap west
shift + alt - l: yabai -m window --swap east

# move window and split
ctrl + alt - j: yabai -m window --warp south
ctrl + alt - k: yabai -m window --warp north
ctrl + alt - h: yabai -m window --warp west
ctrl + alt - l: yabai -m window --warp east

alt - o: yabai -m space --focus next
alt - i: yabai -m space --focus prev

alt - q: yabai -m space --focus 1
alt - w: yabai -m space --focus 2
alt - e: yabai -m space --focus 3
alt - r: yabai -m space --focus 4
alt - t: yabai -m space --focus 5

